import { ISkill } from "@/interfaces/ISkill";

export const skills: ISkill[] = [
  {
    id: 1,
    logo: "/assets/icons/html.svg",
    name: "HTML",
    category: 'language',
  },
  {
    id: 2,
    logo: "/assets/icons/css.svg",
    name: "CSS",
    category: 'language',
  },
  {
    id: 3,
    logo: "/assets/icons/javascript.svg",
    name: "JAVASCRIPT",
    category: 'language',
  },
  {
    id: 4,
    logo: "/assets/icons/typescript.svg",
    name: "TYPESCRIPT",
    category: 'language',
  },
  {
    id: 5,
    logo: "/assets/icons/bootstrap.svg",
    name: "BOOTSTRAP",
    category: 'frameworkAndLibrary',
  },
  {
    id: 6,
    logo: "/assets/icons/tailwind.svg",
    name: "TAILWINDCSS",
    category: 'frameworkAndLibrary',
  },
  {
    id: 7,
    logo: "/assets/icons/nodejs.svg",
    name: "NODEJS",
    category: 'frameworkAndLibrary',
  },
  {
    id: 8,
    logo: "/assets/icons/express.svg",
    name: "EXPRESSJS",
    category: 'frameworkAndLibrary',
  },
  {
    id: 9,
    logo: "/assets/icons/mongoose.svg",
    name: "MONGOOSE",
    category: 'frameworkAndLibrary',
  },
  {
    id: 10,
    logo: "/assets/icons/jasmine.svg",
    name: "JASMINE",
    category: 'frameworkAndLibrary',
  },
  {
    id: 11,
    logo: "/assets/icons/jest.svg",
    name: "JEST",
    category: 'frameworkAndLibrary',
  },
  {
    id: 12,
    logo: "/assets/icons/react.svg",
    name: "REACTJS",
    category: 'frameworkAndLibrary',
  },
  {
    id: 13,
    logo: "/assets/icons/redux.svg",
    name: "REDUX",
    category: 'frameworkAndLibrary',
  },
  {
    id: 14,
    logo: "/assets/icons/next.svg",
    name: "NEXTJS",
    category: 'frameworkAndLibrary',
  },
  {
    id: 15,
    logo: "/assets/icons/mongodb.svg",
    name: "MONGODB",
    category: 'database',
  },
  {
    id: 16,
    logo: "/assets/icons/postgresql.svg",
    name: "POSTGRESQL",
    category: 'database',
  },
  {
    id: 17,
    logo: "/assets/icons/git.svg",
    name: "GIT",
    category: 'tool',
  },
  {
    id: 18,
    logo: "/assets/icons/vite.svg",
    name: "VITEJS",
    category: 'tool',
  },
  {
    id: 19,
    logo: "/assets/icons/figma.svg",
    name: "FIGMA",
    category: 'tool',
  },
  {
    id: 20,
    logo: "/assets/icons/scrum.svg",
    name: "SCRUM",
    category: 'metodology',
  },
  {
    id: 21,
    logo: "/assets/icons/chart.svg",
    name: "CHARTJS",
    category: 'extra',
  },
  {
    id: 22,
    logo: "/assets/icons/websocket.svg",
    name: "WEBSOCKET",
    category: 'extra',
  },
];
